### ISSUE TITLE
issue finding hostpool

### ISSUE THREAD

**Issue by recycleleash** [stephanvandekruis/AVD#1]
Hello there! I have setup AVD via IaC, I have my infra (hp, ws, ag) in a different RG than my compute resources.

I'm getting an error when its trying to find the host pool. I gave the correct permission to the automation account on the subscription level using your json template.

Get-AzWvdSessionHost : Can not perform requested operation on nested resource. Parent resource 'recycleleash-hp' not found. At line:170 char:19 + ... onHosts = @(Get-AzWvdSessionHost -ResourceGroupName $SessionHostrg - ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : InvalidOperation: ({ SubscriptionI...c-CIO-IMIT-hp }:<>f__AnonymousType11`3) [Get-AzWvdSessionHost_List], Exception + FullyQualifiedErrorId : ParentResourceNotFound,Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Cmdlets.GetAzWvdSessionHost_List

![image](https://user-images.githubusercontent.com/99685393/213733429-b4b39a4c-1434-48a8-b906-60656c01b4fe.png)

I have masked the real name of the host pool, but there are definitely hosts on that host pool.

Thanks,
Neil

**Comment by stephanvandekruis** [comment]
Tested and indeed when vms are in an different rg the script is throwing an error.
I have updated the [AVD-PersonalAutoShutdown.ps1](https://github.com/stephanvandekruis/AVD/blob/main/PersonalScaling/AVD-PersonalAutoShutdown.ps1) script
Please update the Runbook in the Automation account with the newest version. You can copy the content of the script and past it into the runbook. Don't forget to press 'Publish'.

Thank you for pointing this out.

**Comment by recycleleash** [comment]
THIS IS AWESOME!!!! Thank you so much for the quick response. It works fantastic!!
